### ISSUE TITLE
Remove $ prefix from property names

### ISSUE THREAD

**Issue by SharpSeeEr** [FrontLabsOfficial/vue-tiny-validate#2]
Remove $ prefix from property names in the following types:
* `Rule`
* `Entry`
* `Result`

Vue 3 has moved away from using it, and with the way the composition API works it is no longer necessary to distinguish global properties.

Obviously, I expect a conversation on this topic before any decisions are made.  Well, hopefully.

**Comment by anh-ld** [comment]
Hi SharpSeeEr. Thank you for your suggestions.

The reason why I put the $ prefix in property names of Entry and Result is to differentiate these properties with data properties.

Lets take a look at the example below

```
const data = reactive({
    test: false,
    invalid: false
})

const rule = reactive({
    test: { $test: value => Boolean(value), $key: 'bool' },
    invalid: { $test: value => Boolean(value), $key: 'bool' },
})

const { result } = useValidate(data, rule)
```

And then the `result` object will be
```
{
    $invalid: false;
    $errors: [];
    $messages: [];
    $pending: false;
    $test: () => void;
    $reset: () => void;
    $touch: () => void;
    test: {
        $invalid: false;
        $errors: [];
        $messages: [];
        $pending: false;
        $test: () => void;
        $reset: () => void;
        $touch: () => void;
    },
    invalid: {
        $invalid: false;
        $errors: [];
        $messages: [];
        $pending: false;
        $test: () => void;
        $reset: () => void;
        $touch: () => void;
    }
}
```

As you can see, if I remove the $ prefix, the `test` method will be replace by the test property. That's not what I want.

Removing $ in the Rule is not a big deal. I'm ok with that thing. However, why I still keep it is because I want to keep property names pattern consistent between objects.

Currently, I haven't found any solution for this problem. So, any ideas?

**Comment by SharpSeeEr** [comment]
Ahhh!  I hadn't considered that aspect of the $ prefix.  Removing the prefix would prevent you from having property names of invalid, errors, messages, pending, etc.  I don't think I've ever had data property names that need to be validated with any of those names, but if you make that a requirement it's guaranteed someone will.  

So for the `Entry` and `Result` types leaving those $ prefixes in place makes sense.  For `Rule` though there aren't any additional properties so the $ could be removed there.

**Comment by SharpSeeEr** [comment]
Sorry!  Was editing my comment as you closed it.

**Comment by anh-ld** [comment]
No worries 😅. I do agree that the $ prefix in `Rule` need to be removed. And the`$key` should be renamed to `name`. 👍

**Comment by anh-ld** [comment]
Updated #6
